#!/bin/bash

function out {
    echo -e '\e[1;'$1'm '$2'\e[m'
}
function info {
    out 34 ">>> $1"
}
function success {
    out 32 "✓ $1"
}
function warn {
    out 33 "[!] $1"
}
function error {
    out 31 "ERROR: $1"
}
function contains {
    has=""
    needle="$1"
    shift
    haystack=$(echo $@ | sed 's/ /\n/g')
    for i in $haystack; do
        if [ "$i" == "$needle" ]; then
            has=1
        fi
    done
    echo $has
}
