#!/bin/bash

function help {
    echo -e '\n Usage: sound-switcher [line|headphones]\n'
}

action=$1
audio_output_file='/tmp/audio_output'

if [ "$action" == "" ]; then # toggle

    if [ ! -f $audio_output_file ]; then
        echo 'h' > $audio_output_file
    fi

    current=$(cat $audio_output_file)
    if [ "$current" == "h" ]; then
        action='l'
    else
        action='h'
    fi
    
fi

automute=$(amixer -c 0 sget "Auto-Mute Mode" | grep Item0 | grep Enabled)
if [ "$automute" != "" ]; then
    amixer -c 0 sset "Auto-Mute Mode" Disabled
fi

if [ "$action" == "line" ] || [ "$action" == "l" ]; then
    #echo 'audio output to line'
    pactl set-sink-port 0 analog-output-lineout
    pactl set-sink-volume 0 40%
    echo l > $audio_output_file

elif [ "$action" == "headphones" ] || [ "$action" == "h" ]; then
    #echo 'audio output to headphones'
    pactl set-sink-port 0 analog-output-headphones
    amixer -c0 sset Front 0 > /dev/null
    pactl set-sink-volume 0 60%
    echo h > $audio_output_file

else
    help
fi
